---

- name: initially setup os
  hosts: status.c3woc.de
  roles:
   - ssh-authorisation
   - sshd
  tags:
   - init
  vars:
    ansible_user: 'root'

- name: install and configure os
  hosts: status.c3woc.de
  roles:
    - base-packages
    - home_enviroment
  tags:
   - os

- name: Deploy grafana
  hosts: status.c3woc.de
  roles:
    - cloudalchemy.grafana
  tags:
   - grafana
  vars_files:
    - vars/grafana.yml


- name: Deploy nginx
  hosts: status.c3woc.de
  roles:
    - le-nginx
  tags:
   - nginx

- name: Deploy influxdb
  hosts: status.c3woc.de
  roles:
    - rossmcdonald.influxdb
  tags:
   - influxdb
 
