---

users:
  l3d:
    - l3d
  ansible:
    - l3d

hostname: 'status.c3woc.de'
grafana_domain: "{{ hostname }}"
domain_name:  "{{ hostname }}"
grafana_auth:
  anonymous:
    org_name: "C3WOC"
    org_role: Viewer
grafana_security:
  admin_user: "{{ vault_grafana_security.admin_user }}"
  admin_password: "{{ vault_grafana_security.admin_password }}"


influxdb_http_https_certificate: "/etc/letsencrypt/live/{{ domain_name }}/privkey.pem"
influxdb_http_https_enabled: "true"

############
# InfluxDB #
############

manala_influxdb_databases:
  - waffel

manala_influxdb_users:
    #  - database: waffel
    # name:     waffel
    # password: 

manala_influxdb_privileges:
  - database: waffel
    user:     waffel
    grant:    ALL

manala_influxdb_config:
  - reporting-disabled: true
  # see: https://docs.influxdata.com/influxdb/v0.13/write_protocols/udp
  - udp:
    - enabled: true
    - bind-address: :8089
    - database: stats
    - batch-size: 5000
    - batch-timeout: 1s
    - batch-pending: 10
    - read-buffer: 0 
