---

users:
  l3d:
    - l3d
  ansible:
    - l3d

hostname: 'status.c3woc.de'
grafana_domain: "{{ hostname }}"
domain_name:  "{{ hostname }}"
grafana_auth:
  anonymous:
    org_name: "C3WOC"
    org_role: Viewer
grafana_security:
  admin_user: "{{ vault_grafana_security.admin_user }}"
  admin_password: "{{ vault_grafana_security.admin_password }}"


influxdb_http_https_certificate: "/etc/letsencrypt/live/{{ domain_name }}/privkey.pem"
influxdb_http_https_enabled: "true"

 
