---

- name: Create a global bashrc configuration
  copy:
    src: 'files/home_environment/bash.bashrc'
    dest: '/etc/bash.bashrc'
    owner: root
    group: root
    mode: 'u=rw,g=r,o=r'

- name: Copy bashrc configuration to admin users
  copy:
    src: 'files/home_environment/bashrc'
    dest: '/home/{{ item }}/.bashrc'
    owner: '{{ item }}'
    group: admins
    mode: 'u=rw,g=r,o='
  with_items: '{{ admins }}'


- name: Copy vimrc configuration to root
  copy:
    src: 'files/home_environment/vimrc'
    dest: '/root/.vimrc'
    owner: root
    group: root
    mode: 'u=rw,g=r,o='

- name: Copy vimrc configuration to admin users
  copy:
    src: 'files/home_environment/vimrc'
    dest: '/home/{{ item }}/.vimrc'
    owner: '{{ item }}'
    group: admins
    mode: 'u=rw,g=r,o='
  with_items: '{{ admins }}'

- name: Copy motd.sh to gateway
  template:
    src: 'files/home_environment/motd.sh'
    dest: '/etc/motd.sh'
    owner: 'root'
    group: 'admins'
    mode: 'u=rwx,g=rx,o='
  register: motdsh

- name: Set fancy motd
  script: 'files/home_environment/motd.sh {{ hostname }}'
  when: motdsh.changed
